blogicum/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from blog import views
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView

app_name = 'blog'
template_str = 'registration/'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/',
         views.PostDetailView.as_view(), name='post_detail'),
    path('posts/<int:post_id>/comment',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/edit_comment/<int:comment_id>/',
         views.edit_comment, name='edit_comment'),
    path('posts/<int:post_id>/delete_comment/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
    path('posts/<int:post_id>/edit/', views.create_edit_post,
         name='edit_post'
         ),
    path('posts/<int:post_id>/delete/', views.post_delete, name='delete_post'),
    path('posts/create/', views.create_edit_post, name='create_post'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('category/<slug:category_slug>/',
         views.category_posts, name='category_posts'),
    path('profile/<str:profile_username>/',
         views.user_profile, name='profile'),
    path('auth/registration/', 
         CreateView.as_view(
             template_name='registration/registration_form.html',
             form_class=UserCreationForm,
             success_url=reverse_lazy('blog:index'),
             ),
             name='registration',
        ),
    path('auth/login/', LoginView.as_view(
        template_name=template_str + 'login.html'),
        name='login'),
    path('auth/logout/', LogoutView.as_view(
        template_name=template_str + 'logged_out.html'),
        name='logout'),
    path('auth/password_change/done/', PasswordChangeDoneView.as_view(
        template_name=template_str + 'password_change_done.html'),
        name='password_change_done'),
    path('auth/password_change/', PasswordChangeView.as_view(
        template_name=template_str + 'password_change_form.html'),
        name='password_change'),
    path('auth/password_reset/complete/', PasswordResetCompleteView.as_view(
        template_name=template_str + 'password_reset_complete.html'),
        name='password_reset_complete'),
    path('auth/password_reset/confirm/', PasswordResetConfirmView.as_view(
        template_name=template_str + 'password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('auth/password_reset/done/', PasswordResetDoneView.as_view(
        template_name=template_str + 'password_reset_done.html'),
        name='password_reset_done'),
    path('auth/password_reset/', PasswordResetView.as_view(
        template_name=template_str + 'password_reset_form.html'),
        name='password_reset'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
    path('', include('blog.urls')),
    path('posts/', include('blog.urls')),
    path('category/', include('blog.urls')),
    path('profile/', include('blog.urls')),
    path('edit_profile/', include('blog.urls')),
    path('auth/', include('blog.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutPage.as_view(), name='about'),
    path('rules/', views.RulesPage.as_view(), name='rules'),
]

blogicum/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
   {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

blogicum/templates/footer.html
<footer class="border-top text-center py-3">
    <p>© Блогикум</p>    
  </footer>

blogicum/templates/header.html
<header>
  {% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          Блогикум
        </a>        
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">
              Лента записей
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pages:rules' %}">
              Наши правила
            </a>
          </li>
        </ul>      
      </div>
    </nav> 